### ISSUE TITLE
 *-workspace-user.USER.pair.sharing.io ingress route from mgmt cluster to created cluster

### ISSUE THREAD

**Issue by hh** [sharingio/coder#12]
#### Outcluster using *.USER.pair.sharing.io

Kubevirt clusters should have a *-workspace-user.USER.pair.sharing.io ingress route from outer cluster to inner.
The inner cluster can be plain http for now.

**Comment by hh** [comment]
Should be able to route to kuberenetes api as well.

**Comment by hh** [comment]
From https://hackmd.io/MYsKUFclTCyU57UU-zKlVQ?both#SSL-ingress

**Comment by BobyMCbobs** [comment]
Giving a go and basic exposing of services out of the Kubevirt VM by using NodePorts.
According to the docs, it appears that services running on ports on the VM can be exposed through Kubernetes services.
I figure that a chain of _code-server container listening process_ -> NodePort on VM -> Service on management cluster -> Ingress on management cluster

There is a service defined like this active
```
apiVersion: v1
kind: Service
metadata:
  name: nc-nodeport
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: nodeport
    nodePort: 31000 # 30000-32767
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: code-server
  type: NodePort
```

and it is accessible in the code-server container on 8080.

But running into this right now, where a process is showing as listening with `ss` but not via `nc`
<img width="576" alt="image" src="https://user-images.githubusercontent.com/8588826/201221229-5a229b2e-03fd-499f-9270-d69124679918.png">

I'm running `nc -l 8080` in the coder-server container and a NodePort service going from 8080 to 31000
